name: OasisGuild
version: ${version}
main: top.oasismc.oasisguild.bukkit.OasisGuild
api-version: 1.13
load: STARTUP
softdepend: [ PlaceholderAPI ]
authors: [ StringStream_, ChiyodaXiaoYi ]
commands:
  guild:
    aliases:
      - g
      - og
permissions:
  oasis.guild.create:
    default: op
  oasis.guild.disband:
    default: op
  oasis.guild.rename:
    default: op
  oasis.guild.admin:
    default: op